- Gemfile
- Gemfile.lock
- コメントを消す
- アルファベット順に並べる
- バージョン指定をしない
> Gemfileをすっきりさせる

- .github/dependabot.yml
> DependabotにGemfileを見てもらう

- app/assets/stylesheets/application.css
- app/controllers/application_controller.rb
- app/controllers/sessions_controller.rb
- app/helpers/session_helper.rb
- app/views/layouts/_login.html.erb
- app/views/layouts/application.html.erb
- app/views/root/index.html.erb
- config/initializers/session_store.rb
- ログイン状態をセッションで表現する
- Memberの一覧を表示する
- ログインしている人だけに情報を見せるよう、表示を整理する
> ログイン状態を管理し、Memberの一覧を表示する

- app/controllers/sessions_controller.rb
- app/views/layouts/_login.html.erb
- config/routes.rb
- https://github.com/teacherteacher-jp/manabiya/pull/6
にて「ログイン」は実装したけれど「ログアウト」の機構はなくて、入ったら出られないという恐怖のつくりになっていたので出口をつくります :joy:
> ログアウト機能を実装する

- app/javascript/application.js
DOMContentLoadedだとTurboのときに反応しないよね、凡ミスでした :pray: :dash:
> Turboによるページ移動のときにも発火させたい

- app/assets/stylesheets/application.css
- app/views/me/index.html.erb
- app/views/schedules/index.html.erb
初見の人でも「何時から何時までか？」を把握できた方がうれしいので :v:
> スケジュール入力フォームには「日付」に加えて「時間帯」も表示する

- config/application.rb
以前に load する処理を入れたけれど、他のリポジトリを触っているときに「不要じゃん」と気付いたので消す :broom:
- https://github.com/teacherteacher-jp/manabiya/pull/24
> dotenvは勝手に読み込んでくれるのでなにもしなくていい

- db/seeds.rb
ぼくが認識している範囲で「いま、あるとよさそう！」なふたつを追加します :singapore: :canada:
> Regionにシンガポールとカナダを追加する

- db/seeds.rb
> Regionにフランスを足す

- app/models/notification.rb
二学期が始まって具体的な要望が出てきたので、実装に反映させていくぞい :muscle:
> ボランティア関連のDiscord通知の内容をブラッシュアップする

- app/models/schedule.rb
タンキュウガクシュウってのは「究める」方の「探究」でした :pray:
> 「探求」じゃなくて「探究」だった

- public/404.html
- public/500.html
利用者のほとんどが日本語話者なので、エラーページを日本語にしておきます。
> エラーページを日本語で用意する

- app/views/members/show.html.erb
- Regionの表示のセンタリングがうまくいっていなかったので、整えたい
- 「編集する」のリンクは自分のページを見ているときだけ表示する
> Memberページ、ちょっと整える

- db/seeds.rb
> C'mon, baby アメリカ

- db/seeds.rb
> Regionを追加しチャイナ

- app/controllers/webhooks/metalife_controller.rb
> MetaLifeの入室通知にURLを添える

- lib/oyasumi.rb
スケジュール入力画面に水曜日の分が表示されなくなるようにします :date:
> 今後、水曜日はボランティア参加の枠がなくなる

- app/controllers/generations_controller.rb
- app/controllers/root_controller.rb
- app/views/generations/index.html.erb
- config/routes.rb
> みんなの参加時期の一覧ページをつくる

- app/controllers/family_members_controller.rb
- app/controllers/my/family_members_controller.rb
- app/javascript/application.js
- app/models/family_member.rb
- app/models/member.rb
- app/models/notification.rb
- app/views/members/show.html.erb
- app/views/my/family_members/index.html.erb
- config/routes.rb
- db/migrate/20241013093336_create_family_members.rb
- db/schema.rb
- test/models/family_member_test.rb
コミュニティでは「小学2年生の息子がいます」「中学3年生の娘がいます」ってのは大事なプロフィールとして機能しているように見えるので、入力できるようにします :family:
> プロフィールの一項目として、家族を登録できるようにする

- Gemfile
- Gemfile.lock
> Ruby 3.3.5

- db/migrate/20241110135358_add_admin_column_to_members_table.rb
- db/schema.rb
このあと「管理者のみに許可された操作」などの制御を入れていきたいので :wave:
> Memberモデルにadminカラムを導入する

- app/controllers/root_controller.rb
- app/views/root/index.html.erb
まじめな認可処理は追ってやるとして、ひとまず表示を制御する :see_no_evil:
> メニューの「みんなのスケジュール」は管理者にだけ表示する

- Gemfile
- Gemfile.lock
> Ruby 3.3.6

- bin/dev
- https://github.com/teacherteacher-jp/manabiya/pull/95
のbin/devの変更で、Development環境でTailwind CSSをうまく扱えなくなってしまっていたっぽい :thinking:
> Rails 8にしたときにbin/devが意図しない形になっていた

- app/models/event.rb
> Eventモデルに、Google Calendarに追加するためのリンクを生成するメソッドを実装する

- app/controllers/events_controller.rb
- app/views/events/index.ics.erb
こいつを各位が使っているカレンダーアプリに登録しておけば予定を把握できるぜ！ってのが成立するのか試したい :muscle:
> イベントの一覧をicalendar形式で返せるようにする

- app/controllers/webhooks/line_controller.rb
- config/environments/development.rb
- config/routes.rb
受け取ったあとの処理は追って実装するとして、まずは受け取れるようにするぞ！という内容です :muscle:
> LINEのMessaging APIのWebhookを受け取りたい

- Gemfile
- Gemfile.lock
> Ruby 3.4.1

- db/seeds.rb
> Regionにインドを足す

- Gemfile
- Gemfile.lock
> Ruby 3.4.2

- Gemfile.lock
最新のBundlerを使いたかったので、いったんGemfile.lockを消してbundle installし直しました。副次的にいくつかのGemのバージョンも上がっています :up:
> BundlerとGemたちのバージョンを上げる

- app/javascript/controllers/character_counter_controller.js
- app/views/students/show.html.erb
- https://github.com/teacherteacher-jp/manabiya/pull/161
の続きです。みなさんに触ってもらって、改善したいところが見つかっているのでやっていきます。
> フリースクールの生徒さんの情報を安全に扱えるようにする - 2周目

- db/seeds.rb
:new_zealand: :new_zealand: :new_zealand:
> Regionにニュージーランドを追加する

- app/controllers/students_controller.rb
- app/models/notification.rb
- app/models/student.rb
- app/views/students/edit.html.erb
- app/views/students/show.html.erb
- config/routes.rb
> Studentの編集機能をつくり、Discord通知の内容を見直す

- db/seeds.rb
:thailand: :thailand: :thailand:
> Regionにタイを追加する

- app/models/assignment.rb
- app/models/notification.rb
「この日のこの枠は◯◯さんにお願いすることになりましたよ」もDiscord通知しておくといいかな、と思う出来事があったので :dizzy:
> Scheduleに対してAssignmentがつくられたらDiscordに通知する

- app/controllers/school_memos_controller.rb
- app/controllers/students_controller.rb
- app/helpers/application_helper.rb
- app/models/notification.rb
- app/models/school_memo.rb
- app/views/school_memos/_block.html.erb
- app/views/school_memos/_form.html.erb
- db/migrate/20250522140928_add_date_to_school_memos.rb
- db/schema.rb
きのうや数日前のメモをさかのぼって投稿することがあるとわかったので、フォームにて「この日の話」を明示できるようにしてみます。フォームにおけるデフォルト値は「今日」にするので、当日のメモであればこれまでと変わらない手数で投稿できます。
> SchoolMemoに「どの日の話か」を入力できるようにする

- Dockerfile
- Gemfile
- Gemfile.lock
> Ruby 3.4.4

- app/controllers/discord/messages_controller.rb
- app/views/discord/messages/new.html.erb
- config/routes.rb
- lib/discord.rb
このあとの作業に役立ちそうだったので、ちょっくら作ります :muscle:
> Discordの任意のチャンネルやスレッドに任意の文字列を送信できるフォームをつくる
